version: '3.3'
services:
    mongodb:
        container_name: mongo
        image: mongo:6.0
        ports:
            - '27017:27017'
        volumes:
            - mongodb_data:/data/db
        networks:
            - sandbox-net
        environment:
            - MONGO_INITDB_ROOT_USERNAME=user
            - MONGO_INITDB_ROOT_PASSWORD=password
        restart: always
networks:
    sandbox-net:

volumes:
    mongodb_data: