logging:
    level.org.springframework: DEBUG

spring:
    application:
        name: "ReactiveProgramming"
    data:
        mongodb:
            uri: 'mongodb://user:password@localhost:27017'
            authentication-database: admin
            database: 'ReactiveProgrammingTest'