server:
    port: 8080

logging:
    level.org.springframework: INFO

spring:
    mvc:
        async:
            request-timeout: 20000
    application:
        name: "ReactiveProgramming"
    data:
        mongodb:
            uri: 'mongodb://devs:password@localhost:27017'
            authentication-database: admin
            database: 'ReactiveProgrammingTest'

management:
    endpoint:
        health:
            probes:
                enabled: true
    health:
        livenessState:
            enabled: true
        readinessState:
            enabled: true
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: info, health, metrics