apiVersion: v1
kind: Service
metadata:
  name: {{ include "sandboxreactiveprogramming.fullname" . }}
  labels:
    {{- include "sandboxreactiveprogramming.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort:  {{ .Values.service.nodePort }}
  selector:
    {{- include "sandboxreactiveprogramming.selectorLabels" . | nindent 4 }}
